---
driver:
  name: vagrant

provisioner:
   name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: default
    run_list:
      - recipe[codenamephp_localmail::postfix]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      codenamephp_localmail:
        postfix:
          local:
            user_relay: root@localhost