addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

if: sender != "github-actions[bot]"

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

services: docker

env:
  global:
    - CHEF_LICENSE=accept
    - KITCHEN_LOCAL_YAML=kitchen.dokken.yml

install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - openssl aes-256-cbc -K $encrypted_4035078d8a92_key -iv $encrypted_4035078d8a92_iv -in codenamephp.pem.enc -out codenamephp.pem -d

script:
  - chef exec foodcritic .
  - chef exec rubocop
  - chef exec rspec
  - chef exec kitchen test

before_deploy:
  - chef exec knife cookbook metadata from file metadata.rb
deploy:
  provider: chef_supermarket
  user_id: "codenamephp"
  client_key: "codenamephp.pem"
  category: "Utilities"
  edge: true
  run:
    - chef exec berks upload -e test
  on:
    tags: true

notifications:
  slack:
    rooms:
      - secure: "ShxxodvpiMlvgXVWCQ7zL7P0iWPAeUvXad+p5ukBtUAGqUSYJ0s5xvG2nWJXqQBCLflJ3CQ0wsJITRFwapqkFzLffhg3CaD6YgEg8B74r08/dU1nbq0chOD32ZnRDxq+ngA8jT5OjFVBPGXx/Zj7MgnDXeM6gqtwNuVldYRnO/jO9ZwJD9SEBYmjoOFlVuH9AOLLaEdpOt433Gmnxx8RRD7wqQ7WFBRC2E6s3SH5YTd/SvbWN+hUqYZaa8Qk0lEnMo3tO6/rxITh1blhStgaV4wYfkJuihF4SwMxeo4116zrWTtrLxqe4+ueAOKY2Qyk++9L7ROLdbSOpLEgwOwmb1BKYvP9IfpMUuyIGAP90/7Wk3fgRe6N4GcyGH9gcjoV+pZgxd3Vkw1ht+3kKuV2A4sXw04uFM0mOUq/bH4+v2JB04JbYqirKUOGPoQFzeWc2B2P64Sf9VOgc+gnfgV9ERUIlrPgV9scCuSXLf3Vf7bdU2U4WGYrqRaJeRPs3P1fx42bptLB5JrvS+z0EIoE6nxrcAr9y0/AppCMGKlx3KQFlzGrzLCg+oSMXzwxa6uUgyHfdvbOFJjoarSA6EftALrXUpmmbrzTc/y5KFlHjjA59bG6ifNFqxmnzuq2w6UciWKqMt00Od4/3W0oltUg5ndi/aeUrmH0GTNYKrAAJ0M="
    on_success: never
    on_failure: always
